### ISSUE TITLE
`bundle exec soloist` throws error about `issues_url`

### ISSUE THREAD

**Issue by thefetts** [pivotal-sprout/sprout-terminal#3]
When trying to follow the readme, I get this error on a fresh MacBook Pro when executing the command `bundle exec soloist`.

```
bundler: failed to load command: soloist (/usr/local/bin/soloist)
NoMethodError: undefined method `issues_url' for #<Chef::Cookbook::Metadata:0x007fa93197a7e8>
  /Users/jerryfallon/workspace/sprout-terminal/tmp/librarian/cache/source/git/b383751a6139f1b4/metadata.rb:11:in `from_file'
  /Library/Ruby/Gems/2.0.0/gems/chef-11.12.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
  /Library/Ruby/Gems/2.0.0/gems/chef-11.12.2/lib/chef/mixin/from_file.rb:30:in `from_file'
  /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/manifest_reader.rb:31:in `compile_manifest'
  /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/manifest_reader.rb:21:in `read_manifest'
  /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/local.rb:57:in `fetch_manifest_data'
  /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/local.rb:49:in `manifest_data'
  /Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/local.rb:28:in `fetch_version'
..........
  /Library/Ruby/Gems/2.0.0/gems/soloist-1.0.3/lib/soloist/cli.rb:35:in `install_cookbooks'
  /Library/Ruby/Gems/2.0.0/gems/soloist-1.0.3/lib/soloist/cli.rb:16:in `chef'
  /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /Library/Ruby/Gems/2.0.0/gems/soloist-1.0.3/bin/soloist:4:in `<top (required)>'
  /usr/local/bin/soloist:23:in `load'
  /usr/local/bin/soloist:23:in `<top (required)>'
```

**Comment by aramprice** [comment]
Closing this as I am about to archive the repo.
